labels:
  metadata:
    color: "EEEEEE"
    description: Relates to package metadata

  buster:
    color: "CE0056"
    description: Debian 10 Buster (oldoldstable)
  bullseye:
    color: "CE0056"
    description: Debian 11 Bullseye (oldstable)
  bookworm:
    color: "CE0056"
    description: Debian 12 Bookworm (stable)
  trixie:
    color: "CE0056"
    description: Debian 13 Trixie (testing)
  sid:
    color: "CE0056"
    description: Debian 14 Sid (unstable)

  buster-updates:
    color: "69012C"
    description: Debian 10 Buster (oldoldstable) Updates
  bullseye-updates:
    color: "69012C"
    description: Debian 11 Bullseye (oldstable) Updates
  bookworm-updates:
    color: "69012C"
    description: Debian 12 Bookworm (stable) Updates
  trixie-updates:
    color: "69012C"
    description: Debian 13 Trixie (testing) Updates
  sid-updates:
    color: "69012C"
    description: Debian 14 Sid (unstable) Updates

  debian-security:
    color: "FC0069"
    description: Security Updates for Debian
  debian-security:buster-security:
    color: "FC0069"
    description: Security Updates for Debian 10 Buster (oldoldstable)
  debian-security:bullseye-security:
    color: "FC0069"
    description: Security Updates for Debian 11 Bullseye (oldstable)
  debian-security:bookworm-security:
    color: "FC0069"
    description: Security Updates for Debian 12 Bookworm (stable)
  debian-security:trixie-security:
    color: "FC0069"
    description: Security Updates for Debian 13 Trixie (testing)
  debian-security:sid-security:
    color: "FC0069"
    description: Security Updates for Debian 14 Sid (unstable)
