name: JSON check

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check JSON Syntax
        uses: limitusus/json-syntax-check@v2
