name: Validate

on:
  pull_request:
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Track changed files
        id: changed-files
        uses: tj-actions/changed-files
        with:
          files: |
            !apt/**

      - name: Check changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Detected changes outside of /apt/ directory!"
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          exit 1

      - name: Set up NodeJS
        uses: actions/setup-node

      - name: Validate
        run: |
          npx --package @apt-repositories/generator --command validate ./apt
