name: Validate

on:
  pull_request:
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          # renovate: datasource=docker depName=node versioning=node
          node-version: "20.12.2"

      - name: Validate
        run: |
          npx --package @apt-repositories/generator --command validate ./apt
